INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @duhovnyjpomoshnikbot id=6224388943 - 'Духовный Помощник 🕊'
INFO:aiogram.event:Update id=87462679 is handled. Duration 107 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462680 is handled. Duration 391 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462681 is handled. Duration 322 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462682 is handled. Duration 293 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462683 is handled. Duration 474 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462684 is handled. Duration 100 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462685 is handled. Duration 61 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462686 is handled. Duration 182 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462687 is handled. Duration 255 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462688 is handled. Duration 172 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462689 is handled. Duration 173 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462690 is handled. Duration 166 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462691 is handled. Duration 169 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462692 is handled. Duration 226 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462693 is handled. Duration 279 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462694 is handled. Duration 288 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462695 is handled. Duration 191 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462696 is handled. Duration 127 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462697 is handled. Duration 127 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462698 is handled. Duration 499 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462699 is handled. Duration 186 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462700 is handled. Duration 392 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462701 is handled. Duration 457 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462702 is handled. Duration 120 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462703 is handled. Duration 125 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462704 is handled. Duration 95 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462705 is handled. Duration 162 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462706 is handled. Duration 115 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462707 is handled. Duration 110 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462708 is not handled. Duration 7 ms by bot id=6224388943
ERROR:aiogram.event:Cause exception while process update id=87462708 by bot id=6224388943
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/templs/templs-bot/core/handlers/callbacks.py", line 257, in create_order
    total_price = order_total // 100
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
INFO:aiogram.event:Update id=87462709 is handled. Duration 90 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462710 is handled. Duration 123 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462711 is handled. Duration 296 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462712 is handled. Duration 77 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462713 is handled. Duration 111 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462714 is handled. Duration 371 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462715 is handled. Duration 480 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462716 is handled. Duration 97 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462717 is handled. Duration 217 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462718 is handled. Duration 181 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462719 is handled. Duration 88 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462720 is not handled. Duration 7 ms by bot id=6224388943
ERROR:aiogram.event:Cause exception while process update id=87462720 by bot id=6224388943
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/templs/templs-bot/core/handlers/callbacks.py", line 257, in create_order
    total_price = order_total // 100
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
INFO:aiogram.event:Update id=87462721 is handled. Duration 65 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462722 is handled. Duration 287 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462723 is handled. Duration 241 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462724 is handled. Duration 104 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462725 is handled. Duration 131 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462726 is handled. Duration 88 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462727 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462728 is handled. Duration 127 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462729 is handled. Duration 105 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462730 is handled. Duration 102 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462731 is handled. Duration 115 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462732 is handled. Duration 471 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462733 is handled. Duration 137 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462734 is handled. Duration 230 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462735 is handled. Duration 395 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462736 is handled. Duration 81 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462737 is handled. Duration 258 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462738 is handled. Duration 103 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462739 is handled. Duration 103 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462740 is handled. Duration 239 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462741 is handled. Duration 83 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462742 is handled. Duration 257 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462743 is handled. Duration 92 ms by bot id=6224388943
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
INFO:aiogram.event:Update id=87462744 is handled. Duration 129 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462745 is handled. Duration 213 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462746 is handled. Duration 298 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462747 is handled. Duration 161 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462748 is handled. Duration 290 ms by bot id=6224388943
Settings(bots=Bots(bot_token='6224388943:AAGBghZDdulqRpZuH7DZnOorzsd14vEsRL4', admin_id=5724326916, provider_token='401643678:TEST:a5e472fa-a2a7-461e-ba91-4a077ff53e1e'))
2024-04-07 15:56:59
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Троицкая церковь, За здравие, Россия, Казань, Поставить свечу, Месячный
Троицкая церковь, За здравие, Россия, Казань, Поставить свечу, Полгода
Троицкая церковь, За здравие, Россия, Казань, Поставить свечу, Разовый
Троицкая церковь, За здравие, Россия, Казань, Поставить свечу, Год
2024-04-07 16:08:52
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Храм Гроба Христа Господня, За здравие и упокой, Израиль, None, Поставить свечу, Месячный
Храм Гроба Христа Господня, За здравие и упокой, Израиль, None, Поставить свечу, Разовый
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
2024-04-07 23:01:05
2024-04-07 23:54:01
2024-04-08 04:19:55
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
INFO:aiogram.event:Update id=87462749 is handled. Duration 155 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462750 is handled. Duration 94 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462751 is handled. Duration 132 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462752 is handled. Duration 142 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462753 is handled. Duration 43 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462754 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462755 is handled. Duration 267 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462756 is handled. Duration 270 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462757 is handled. Duration 128 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462758 is handled. Duration 128 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462759 is handled. Duration 100 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462760 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462761 is handled. Duration 146 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462762 is handled. Duration 57 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462763 is handled. Duration 102 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462764 is handled. Duration 280 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462765 is handled. Duration 298 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462766 is handled. Duration 182 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462767 is handled. Duration 99 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462768 is handled. Duration 108 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462769 is handled. Duration 137 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462770 is handled. Duration 120 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462771 is handled. Duration 261 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462772 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462773 is handled. Duration 65 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462774 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462775 is handled. Duration 446 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462776 is handled. Duration 324 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462777 is handled. Duration 276 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462778 is handled. Duration 119 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462779 is handled. Duration 157 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462780 is handled. Duration 227 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462781 is handled. Duration 146 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462782 is handled. Duration 169 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462783 is handled. Duration 100 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462784 is handled. Duration 90 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462785 is handled. Duration 98 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462786 is handled. Duration 208 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462787 is handled. Duration 237 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462788 is handled. Duration 119 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462789 is handled. Duration 93 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462790 is handled. Duration 100 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462791 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462792 is handled. Duration 103 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462793 is handled. Duration 123 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462794 is handled. Duration 150 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462795 is handled. Duration 88 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462796 is handled. Duration 98 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462797 is handled. Duration 94 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462798 is handled. Duration 110 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462799 is handled. Duration 176 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462800 is handled. Duration 113 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462801 is handled. Duration 170 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462802 is handled. Duration 140 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462803 is handled. Duration 143 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462804 is handled. Duration 122 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462805 is handled. Duration 94 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462806 is handled. Duration 86 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462807 is handled. Duration 82 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462808 is handled. Duration 106 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462809 is handled. Duration 110 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462810 is handled. Duration 90 ms by bot id=6224388943
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Храм Христа Спасителя, Семейное благополучие, Россия, Москва, Подать записку, Разовый
2024-04-08 17:08:17
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Храм Христа Спасителя, Семейное благополучие, Россия, Москва, Подать записку, Разовый
2024-04-08 17:17:58
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Храм Христа Спасителя, Семейное благополучие, Россия, Москва, Подать записку, Разовый
2024-04-08 17:26:33
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
INFO:aiogram.event:Update id=87462811 is handled. Duration 96 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462812 is handled. Duration 160 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462813 is handled. Duration 147 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462814 is handled. Duration 105 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462815 is handled. Duration 250 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462816 is handled. Duration 164 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462817 is handled. Duration 106 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462818 is handled. Duration 49 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462819 is handled. Duration 155 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462820 is handled. Duration 84 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462821 is handled. Duration 358 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462822 is handled. Duration 227 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462823 is handled. Duration 103 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462824 is handled. Duration 124 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462825 is handled. Duration 128 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462826 is handled. Duration 94 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462827 is handled. Duration 150 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462828 is handled. Duration 52 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462829 is handled. Duration 173 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462830 is handled. Duration 292 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462831 is handled. Duration 207 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462832 is handled. Duration 192 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462833 is handled. Duration 128 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462834 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462835 is handled. Duration 109 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462836 is handled. Duration 190 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462837 is handled. Duration 50 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462838 is handled. Duration 144 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462839 is handled. Duration 243 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462840 is handled. Duration 265 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462841 is handled. Duration 209 ms by bot id=6224388943
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
INFO:aiogram.event:Update id=87462842 is handled. Duration 263 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462843 is handled. Duration 311 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462844 is handled. Duration 169 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462845 is handled. Duration 203 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462846 is handled. Duration 136 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462847 is handled. Duration 91 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462848 is handled. Duration 93 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462849 is handled. Duration 133 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462850 is handled. Duration 124 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462851 is handled. Duration 90 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462852 is handled. Duration 342 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462853 is handled. Duration 539 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462854 is handled. Duration 334 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462855 is handled. Duration 234 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462856 is handled. Duration 337 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462857 is handled. Duration 240 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462858 is handled. Duration 100 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462859 is handled. Duration 67 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462860 is handled. Duration 243 ms by bot id=6224388943
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6224388943)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 6224388943)
INFO:aiogram.event:Update id=87462861 is handled. Duration 146 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462862 is handled. Duration 305 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462863 is handled. Duration 419 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462864 is handled. Duration 88 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462865 is handled. Duration 111 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462866 is handled. Duration 165 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462867 is handled. Duration 168 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462868 is handled. Duration 60 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462869 is handled. Duration 90 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462870 is handled. Duration 100 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462871 is handled. Duration 176 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462872 is handled. Duration 113 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462873 is handled. Duration 60 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462874 is handled. Duration 423 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462875 is handled. Duration 131 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462876 is handled. Duration 44 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462877 is handled. Duration 140 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462878 is handled. Duration 110 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462879 is handled. Duration 86 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462880 is handled. Duration 325 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462881 is not handled. Duration 190 ms by bot id=6224388943
ERROR:aiogram.event:Cause exception while process update id=87462881 by bot id=6224388943
AttributeError: 'InaccessibleMessage' object has no attribute 'answer_photo'
Traceback (most recent call last):
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/pydantic/main.py", line 753, in __getattr__
    return pydantic_extra[item]
KeyError: 'answer_photo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/templs/templs-bot/core/handlers/callbacks.py", line 71, in get_services_inline_keyboard
    await send_message_with_photo_and_add_to_delete(call, bot, 'assets/img/services.png', SERVICES_MESSAGE,
  File "/usr/templs/templs-bot/core/handlers/callbacks.py", line 56, in send_message_with_photo_and_add_to_delete
    message = await call.message.answer_photo(photo=photo, caption=caption, reply_markup=keyboard)
  File "/usr/templs/templs-bot/.venv/lib/python3.10/site-packages/pydantic/main.py", line 755, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'InaccessibleMessage' object has no attribute 'answer_photo'
INFO:aiogram.event:Update id=87462882 is handled. Duration 95 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462883 is handled. Duration 344 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462884 is handled. Duration 166 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462885 is handled. Duration 139 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462886 is handled. Duration 130 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462887 is handled. Duration 138 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462888 is handled. Duration 124 ms by bot id=6224388943
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Спасо-Ефросиньевский монастырь, Семейное благополучие, Беларусь, Полоцк, Подать записку, Разовый
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
2024-04-08 18:41:47
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Храм Христа Спасителя, Семейное благополучие, Россия, Москва, Подать записку, Разовый
2024-04-08 19:45:02
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Храм Христа Спасителя, Семейное благополучие, Россия, Москва, Подать записку, Разовый
2024-04-08 19:55:48
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
2024-04-08 20:09:23
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message can't be deleted for everyone
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message can't be deleted for everyone
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Жировичский монастырь, Семейное благополучие, Беларусь, Жировичи, Подать записку, Разовый
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
2024-04-11 23:43:29
Ошибка при удалении сообщений: Telegram server says - Bad Request: message can't be deleted for everyone
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
2024-04-11 23:44:24
2024-04-12 22:23:08
Ошибка при удалении сообщений: Telegram server says - Bad Request: message can't be deleted for everyone
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Храм Гроба Христа Господня, За здравие и упокой, Израиль, None, Поставить свечу, Год
2024-04-13 02:26:32
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
2024-04-13 02:26:49
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
2024-04-13 02:26:55
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: 'InaccessibleMessage' object has no attribute 'delete'
Ошибка при удалении сообщений: Telegram server says - Bad Request: message identifiers are not specified
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
Ошибка при удалении вызывающего сообщения: Telegram server says - Bad Request: message to delete not found
INFO:aiogram.event:Update id=87462889 is handled. Duration 276 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462890 is handled. Duration 93 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462891 is handled. Duration 88 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462892 is handled. Duration 96 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462893 is handled. Duration 171 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462894 is handled. Duration 100 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462895 is handled. Duration 267 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462896 is handled. Duration 389 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462897 is handled. Duration 120 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462898 is handled. Duration 110 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462899 is handled. Duration 98 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462900 is handled. Duration 87 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462901 is handled. Duration 45 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462902 is handled. Duration 44 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462903 is handled. Duration 97 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462904 is handled. Duration 379 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462905 is handled. Duration 209 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462906 is handled. Duration 1182 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462907 is handled. Duration 268 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462908 is handled. Duration 168 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462909 is handled. Duration 114 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462910 is handled. Duration 255 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462911 is handled. Duration 102 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462912 is handled. Duration 141 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462913 is handled. Duration 314 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462914 is handled. Duration 214 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462915 is handled. Duration 417 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462916 is handled. Duration 221 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462917 is handled. Duration 336 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462918 is handled. Duration 179 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462919 is handled. Duration 146 ms by bot id=6224388943
INFO:aiogram.event:Update id=87462920 is handled. Duration 155 ms by bot id=6224388943
